services:
  database:
    image: postgres
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=careeraft
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
